Repository schubergphilis/terraform-azure-mcaf-private-endpoints, pull requests merged in 2024-11, with the labels that each got.

#3 feat: adding private link service
  README.md
  examples/basic/main.tf
  main.tf
  outputs.tf
  tests/basic.tftest.hcl
  variables.tf
Labels: feature

#5 Update main.tf
  README.md
  main.tf
  variables.tf
Labels: bug

#6 feat: replace regex with provider function
  examples/basic/main.tf
  main.tf
  terraform.tf
  variables.tf
Labels: enhancement, feature

#7 bug: put default for location
  variables.tf
Labels: bug

#8 bug: fix location
  main.tf
Labels: bug
